# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# specific branch build with batching
# trigger:
#   batch: true
#   branches:
#     include:
#     - master

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UseDotNet@2
  displayName: .NET Version
  inputs:
    packageType: 'sdk'
    # version: '$(DOTNET_VERSION)'
    version: 8.x
  
- task: Bash@3
  displayName: Install MAUI Workloads
  inputs:
    targetType: 'inline'
    script: |
      dotnet nuget local all --clear
      dotnet workloads install android maui --source https://aka.ms/dotnet8/nuget/index.json --source https://api.nuget.org/v3/index.json

- task: Bash@3
  displayName: Show current working directory
  inputs:
    targetType: 'inline'
    script: 'ls'